---
- name: PAN Initial Setup Playbook
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    panos_install_version: 
    provider:
        ip_address: 192.168.32.130
        username: admin
        password: admin

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: gather panos facts
      panos_facts:
        provider: '{{ provider }}'
        gather_subset: all
      debug:
        msg: "Current PANOS is {{ ansible_net_version }}"

    - name: install pan-os 8.1.6 and restart
      panos_software:
        provider: '{{ provider }}'
        version: '{{ panos_install_version }}'
        restart: true
      when: ansible_net_version > panos_install_version

    - name: wait for ssh and check if device is ready following reboot
      wait_for: port=22 host='{{ provider.ip_address }}' search_regex=SSH timeout=600
      panos_check:
        provider: '{{ provider }}'
      register: result
      until: not result|failed
      retries: 10
      delay: 30

    - name: configure management settings
      panos_mgtconfig:
        provider: '{{ provider }}'
        hostname: '{{ pan_hostname }}'
        timezone: '{{ pan_timezone }}'
        dns_server_primary: '{{ pan_dns_server_primary }}'
        dns_server_secondary: '{{ pan_dns_server_secondary }}'
        domain: '{{ pan_domain }}'
        ntp_server_primary: '{{ pan_ntp_server_primary }}'
        ntp_server_secondary: '{{ pan_ntp_server_secondary }}'

    - name: add siriusadmin
      panos_administrator:
        provider: '{{ provider }}'
        admin_username: 'testadmin'
        admin_password: '{{ siriusadmin_password }}'
        superuser: true
        commit: false

    - name: commit canidate config on firewall
      panos_commit:
        provider: '{{ provider }}'