---
- name: PAN Initial Setup Playbook
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    panos_install_version: 9.0.3
    provider:
        ip_address: 192.168.32.10
        username: admin
        password: admin

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:

#    - name: check if ready
#      panos_check:
#        provider: '{{ provider }}'
#        timeout: 60

    - name: gather panos facts
      panos_facts:
        provider: '{{ provider }}'
        gather_subset: all

    - name: current panos version
      debug:
        msg: "Current PANOS is {{ ansible_net_version }}"

    - name: install pan-os 8.1.6 and restart
      panos_software:
        provider: '{{ provider }}'
        version: '{{ panos_install_version }}'
        restart: false
        install: false
      #when: ansible_net_version > panos_install_version

