---
- name: PAN Initial Setup Playbook
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    panos_install_version: 
    provider:
        ip_address: 192.168.32.10
        username: admin
        password: admin

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: configure management settings
      panos_mgtconfig:
        provider: '{{ provider }}'
        #hostname: '{{ pan_hostname }}'
        #timezone: '{{ pan_timezone }}'
        dns_server_primary: 8.8.8.8
        dns_server_secondary: 4.2.2.2
        #domain: '{{ pan_domain }}'
        #ntp_server_primary: '{{ pan_ntp_server_primary }}'
        #ntp_server_secondary: '{{ pan_ntp_server_secondary }}'

    #- name: commit canidate config on firewall
      #panos_commit:
        #provider: '{{ provider }}'

    - name: check if ready
      panos_check:
        provider: '{{ provider }}'
        timeout: 60

    - name: gather panos facts
      panos_facts:
        provider: '{{ provider }}'
        gather_subset: all

    - name: current panos version
      debug:
        msg: "Current PANOS is {{ ansible_net_version }}"

    - name: install pan-os 8.1.6 and restart
      panos_software:
        provider: '{{ provider }}'
        version: 9.0.3
        restart: false
        install: false
      #when: ansible_net_version > panos_install_version

